package com.AutomatedMeetingBookingSystem.model;

public enum MeetingType {
	
	CLASSROOMTRAINING("CLASSROOMTRAINING"), ONLINETRAINING("ONLINETRAINING"), CONFERENCECAL("CONFERENCECAL"), BUSINESS("BUSINESS") , CONFERENCECALL("CONFERENCECALL");

	MeetingType(String string) {
	}
}